"""adding data

Revision ID: 0ffda94a1d20
Revises: 61ea3271bcec
Create Date: 2023-06-08 12:29:32.766992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffda94a1d20'
down_revision = '61ea3271bcec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
