"""finance migration data

Revision ID: 35324eda1675
Revises: 393cf73484f0
Create Date: 2023-06-07 16:12:52.398207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35324eda1675'
down_revision = '393cf73484f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('transactions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.VARCHAR(), nullable=True))
    op.alter_column('transactions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
